# Generated by Django 6.1 on 2026-08-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=12, max_digits=24)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto.snapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'symbol'), name='unique_symbol_snapshot')],
            },
        ),
    ]
