# Generated by Django 6.1 on 2026-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='source',
            field=models.CharField(default='coingecko', max_length=30),
            preserve_default=False,
        ),
    ]
