# Generated by Django 6.1 on 2026-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_snapshot_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(choices=[('coingecko', 'coingecko'), ('coinmarketcap', 'coinmarketcap')], max_length=30),
        ),
    ]
