# Generated by Django 6.1 on 2026-09-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_watchlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
